### PR TITLE
fix(sbb-dialog, sbb-overlay, sbb-toast): afterClose event not emitting

### LINKED ISSUE #203: chore(sbb-dialog, sbb-overlay, sbb-toast): find better way to test observables
Investigate how to properly test observables for overlay services (`sbb-dialog`, `sbb-overlay`, `sbb-toast`).

The following issue only occurs in test environment, the affected test cases are: 
- “should emit when dialog opening animation is complete”
- “should emit before and after dialog closing animation”

After opening any overlay with the provided service, the user should be able to subscribe to the  `afterOpen`, `beforeClose` and `afterClose` properties available in the SbbOverlayRef, returned by the open method.

However, the observables `afterOpen` and `afterClose` don’t seem to trigger their callback functions properly in test environment.

### LINKED ISSUE #205: [Bug]: SbbOverlayRef afterClose is not emitted
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

lyne-elements: 3.11.0, lyne-angular: 20.0.0-rc.8

### Operating system

Windows 11

### Browser / Browser version

Version 141.0.7390.77 (Offizieller Build) (64-Bit)

### Input mode

Mouse/Keyboard

### Additional settings

_No response_

### What happened?

When using the new SbbDialogService with lyne-angular, the afterClose event is not emitted when closing the dialog. This applies to both closing via the `sbb-dialog-close` directive and closing via the SbbOverlayRef close method. The dialog itself behaves as expected, but the event is simply not emitted. The other two events work.

```
    const dialogRef = this.dialogService.open(AbortDialogComponent);

    dialogRef.afterOpen
      .pipe(
        tap((e) => console.log('afterOpen', e)),
        takeUntil(this.destroyed$)
      )
      .subscribe();

    dialogRef.beforeClose
      .pipe(
        tap((e) => console.log('beforeClose', e)),
        takeUntil(this.destroyed$)
      )
      .subscribe();

    dialogRef.afterClose
      .pipe(
        tap((e) => console.log('afterClose', e)),
        takeUntil(this.destroyed$)
      )
      .subscribe();
```

### Steps to reproduce the issue

1. use SbbDialogService in a component to open a dialog by component reference
2. listen on afterOpen, beforeClose and afterClose events of the returned SbbOverlayRef
3. open and close the dialog
4. check the emitted events

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by MarioCastigliano**
New workflow to avoid disposing of the component before afterClose event has been emitted

BREAKING CHANGE: added new parameter to SbbOverlayRef class.

Closes #205
Closes #203

### CODE REVIEW

File: src/angular/core/overlay/overlay-ref.ts [hunk 1]
```diff
@@ -23,13 +24,26 @@ export class SbbOverlayRef<T = unknown> {
...
   ) {
     this.id = config.id;
     this.#container = container;
+    this.#afterOpen = this.#container.afterOpen.pipe(take(1), share());
+    this.#beforeClose = this.#container.beforeClose.pipe(take(1), share());
+    this.#afterClose = this.#container.afterClose.pipe(take(1), share());
+
+    this.#afterClose.subscribe({
+      complete: () => {
+        overlayRef.dispose();
```
Comment (jeripeierSBB) [inline src/angular/core/overlay/overlay-ref.ts]: only because I'm curious, what is the difference between dispose and detach?

**Review by jeripeierSBB — APPROVED** [review]
As far as I can tell, it looks good :) Thank you!

Double check with @kyubisation ?
